import { createRef } from "react";
import type { Editor } from "@tiptap/core";
import { closeHistory } from "@tiptap/pm/history";
import { act, fireEvent, render, renderHook, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import { VisualEditor, type VisualEditorHandle } from "./VisualEditor";
import { serializeChecklist } from "./checklist";
import { useEditSession } from "./useEditSession";
import { resetTabsStoreForTests, useTabsStore } from "@/stores/tabsStore";

const initial = serializeChecklist({ title: "", items: [{ text: "", checked: false }], html: null });
describe("ChecklistView", () => {
  it("changes draft attributes, navigates, adds/removes rows, splits pasted text and uses node history", async () => {
    vi.useFakeTimers();
    resetTabsStoreForTests();
    useTabsStore.getState().openNote("checklist", { editBase: { html: `<main id="htnote-content">${initial}</main>`, css: null, js: null, contentHash: "base" } });
    const { result, unmount: unmountHook } = renderHook(() => useEditSession("checklist"));
    const ref = createRef<VisualEditorHandle>();
    const { unmount } = render(<VisualEditor ref={ref} initialInner={initial} onChange={result.current.onVisualChange} />);
    const editor = (screen.getByRole("textbox", { name: "Not içeriği" }) as HTMLElement & { editor: Editor }).editor;
    const fields = () => screen.queryAllByTestId("checklist-item") as HTMLInputElement[];
    try {
      await act(async () => { fireEvent.change(screen.getByTestId("checklist-title"), { target: { value: "Saved title" } }); });
      await act(async () => { fireEvent.keyDown(screen.getByTestId("checklist-title"), { key: "Enter" }); });
      expect(fields()[0]).toHaveFocus();
      const first = fields()[0];
      await act(async () => { fireEvent.change(first, { target: { value: "first" } }); });
      expect(fields()[0]).toBe(first);
      await act(async () => { fireEvent.click(screen.getByRole("checkbox")); });
      await act(async () => { fireEvent.keyDown(fields()[0], { key: "Enter" }); });
      expect(fields()).toHaveLength(2);
      expect(fields()[1]).toHaveFocus();
      await act(async () => { fireEvent.keyDown(fields()[1], { key: "ArrowUp" }); });
      expect(fields()[0]).toHaveFocus();
      await act(async () => { fireEvent.keyDown(fields()[0], { key: "ArrowDown" }); });
      expect(fields()[1]).toHaveFocus();
      await act(async () => { fireEvent.keyDown(fields()[1], { key: "Backspace" }); });
      expect(fields()).toHaveLength(1);
      expect(fields()[0]).toHaveFocus();
      fields()[0].setSelectionRange(0, 5);
      await act(async () => { fireEvent.paste(fields()[0], { clipboardData: { getData: () => "a <&>\r\nb\rc\n" } }); });
      expect(editor.state.doc.firstChild?.attrs.items).toEqual([{ text: "a <&>", checked: true }, { text: "b", checked: false }, { text: "c", checked: false }, { text: "", checked: false }]);
      await act(async () => { fireEvent.click(screen.getByRole("button", { name: "Widget arka planı" })); });
      await act(async () => { fireEvent.click(screen.getByRole("button", { name: "Nane" })); });
      act(() => { ref.current?.flush(); vi.advanceTimersByTime(150); });
      expect(useTabsStore.getState().isDirty("checklist")).toBe(true);
      expect(useTabsStore.getState().tabs[0].doc.draft?.html).toContain("a &lt;&amp;&gt;");
      expect(useTabsStore.getState().tabs[0].doc.draft?.html).toContain('data-htnote-bg="mint"');
      act(() => editor.view.dispatch(closeHistory(editor.state.tr)));
      await act(async () => { fireEvent.change(fields()[1], { target: { value: "changed" } }); });
      await act(async () => { fireEvent.keyDown(fields()[1], { key: "z", ctrlKey: true }); });
      expect(fields()[1].value).toBe("b");
      await act(async () => { fireEvent.keyDown(fields()[1], { key: "y", ctrlKey: true }); });
      expect(fields()[1].value).toBe("changed");
      const shortcut = new KeyboardEvent("keydown", { key: "s", ctrlKey: true, bubbles: true, cancelable: true });
      fields()[0].dispatchEvent(shortcut);
      expect(shortcut.defaultPrevented).toBe(false);
      await act(async () => { fireEvent.keyDown(fields()[3], { key: "ArrowDown" }); });
      expect(editor.state.selection.$from.parent.type.name).toBe("paragraph");
      await act(async () => { fireEvent.keyDown(fields()[0], { key: "ArrowUp" }); });
      expect(editor.state.doc.firstChild?.type.name).toBe("paragraph");
      for (let index = fields().length; index > 0; index--) await act(async () => { fireEvent.click(screen.getByRole("button", { name: `Madde ${index} sil` })); });
      expect(fields()).toHaveLength(1);
      expect(fields()[0].value).toBe("");
      await act(async () => { fireEvent.click(screen.getByRole("button", { name: "Madde ekle" })); });
      expect(fields()).toHaveLength(2);
      expect(fields()[1]).toHaveFocus();
    } finally { unmount(); unmountHook(); resetTabsStoreForTests(); vi.useRealTimers(); }
  });
});
