import assert from "node:assert/strict";
import { join } from "node:path";
import { createNote, editNote, openNote, saveAndView, useTempRoot, visibleEditorContentControl, visibleEditorTool, waitForFile, withNoteFrame, invoke } from "../helpers/flows";
import { pointerClickAt, pointerDrag, pointerMoveTo, waitForPointerStable } from "../helpers/pointer";

describe("widget flows", () => {
  let root: string;
  let restore: (() => Promise<void>) | undefined;
  let language: string | null;
  // Pin labels and calculation number formatting independently of the OS locale.
  before(async () => {
    ({ language } = await invoke<{ language: string | null }>("get_settings"));
    await invoke("update_settings", { patch: { language: "tr" } });
  });
  after(async () => { await invoke("update_settings", { patch: { language } }); });
  // Her test kendi köküyle başlar: düşen bir testin kirli taslağı yenilemede kurtarma
  // diyaloğu açıp sonraki testleri engellemez (diğer akış spec'leriyle aynı yol).
  beforeEach(async () => { ({ root, restore } = await useTempRoot()); });
  afterEach(async () => { await restore?.(); restore = undefined; });

  it("saves an IP block, copies live addresses, validates the gateway and restores defaults", async () => {
    const note = await createNote("IP block round trip");
    await openNote(note.id); await editNote();
    await (await visibleEditorTool('[data-testid="insert-widget"]')).click();
    await $('[data-testid="insert-ipblock"]').click();
    const title = await $('[data-testid="ipblock-title"]'); await title.waitForDisplayed();
    await title.setValue("VLAN 106");
    await $('[data-testid="ipblock-gateway"]').setValue("10.67.106.14");
    await $('[data-testid="ipblock-prefix"]').selectByAttribute("value", "30");
    assert.equal(await $('[data-testid="ipblock-count"]').getText(), "1 adres");
    await $('[data-testid="ipblock-prefix"]').selectByAttribute("value", "28");
    await browser.waitUntil(async () => await $('[data-testid="ipblock-count"]').getText() === "13 adres");
    const html = await saveAndView(note.id, (value) => value.includes('data-htnote-gw="10.67.106.14"') && value.includes('data-htnote-prefix="28"'));
    assert.match(html, /<pre class="htnote-ipblock-list">10\.67\.106\.1\n/);
    assert.ok(!html.includes("htnote-ipblock-node"));
    const exportedPath = join(root, "ipblock-export.html");
    await invoke("export_single_html", { id: note.id, targetPath: exportedPath });
    const exported = (await waitForFile(exportedPath)).toString();
    assert.ok(exported.includes('<pre class="htnote-ipblock-list">10.67.106.1\n'));
    assert.ok(!exported.includes("/__htnote/bridge.js"));
    await withNoteFrame(note.id, async () => {
      const gateway = await $('[data-testid="ipblock-gateway"]'), prefix = await $('[data-testid="ipblock-prefix"]');
      const list = await $('[data-testid="ipblock-list"]'), copy = await $('[data-testid="ipblock-copy"]'), reset = await $('[data-testid="ipblock-reset"]');
      await copy.waitForExist();
      assert.equal((await list.getText()).split("\n").length, 13);
      assert.equal(await reset.isEnabled(), false);
      assert.equal(await $('[data-testid="ipblock-summary"]').getText(), "Blok 10.67.106.0/28 · 13 adres (ağ, yayın ve GW hariç)");
      await prefix.selectByAttribute("value", "30");
      await browser.waitUntil(async () => await list.getText() === "10.67.106.13");
      await gateway.setValue("10.67.106.13");
      await browser.waitUntil(async () => await list.getText() === "10.67.106.14");
      await copy.click(); await browser.waitUntil(async () => /Kopyalandı|Copied/.test(await copy.getText()));
      await browser.execute(() => { const probe = document.createElement("textarea"); probe.id = "ipblock-probe"; document.body.append(probe); });
      const probe = await $('#ipblock-probe'); await probe.click(); await browser.keys(["Control", "v"]);
      await browser.waitUntil(async () => await probe.getValue() === "10.67.106.14");
      await browser.execute(() => document.getElementById("ipblock-probe")?.remove());
      await gateway.setValue("10.67.106.12");
      await browser.waitUntil(async () => !(await copy.isEnabled()));
      assert.equal(await gateway.getAttribute("aria-invalid"), "true"); assert.equal(await list.getText(), "");
      await reset.click();
      assert.equal(await gateway.getValue(), "10.67.106.14"); assert.equal(await prefix.getValue(), "28");
      assert.equal((await list.getText()).split("\n").length, 13); assert.equal(await reset.isEnabled(), false);
      await gateway.setValue("10.67.106.13");
    });
    assert.equal((await invoke<{ html: string }>("read_note", { id: note.id })).html, html);
    assert.equal((await waitForFile(join(root, note.relPath, "index.html"))).toString(), html);
    await browser.refresh(); await openNote(note.id);
    await withNoteFrame(note.id, async () => { assert.equal(await $('[data-testid="ipblock-gateway"]').getValue(), "10.67.106.14"); });
    await editNote(); assert.equal(await $('[data-testid="ipblock-title"]').getValue(), "VLAN 106");
    assert.equal(await $('[data-testid="ipblock-prefix"]').getValue(), "28"); await $('[data-testid="cancel-edit"]').click();
  });

  it("creates a board at a block edge, moves a checklist into it and extracts a paragraph", async () => {
    const note = await createNote("Block pointer round trip");
    await openNote(note.id); await editNote();
    await (await visibleEditorContentControl('.tiptap > p')).click();
    await browser.keys("First block"); await browser.keys("Enter"); await browser.keys("Second block");
    const second = await $('.tiptap > p:last-child'); await pointerMoveTo(second);
    const handle = await $('[data-testid="block-handle"]'); await handle.waitForDisplayed();
    const edge = await browser.execute(() => { const rect = document.querySelector('.tiptap > p')!.getBoundingClientRect(); return { x: Math.round(rect.right - 8), y: Math.round(rect.top + rect.height / 2) }; });
    await pointerDrag(handle, await $('.tiptap > p'), { toPoint: edge });
    await $('.tiptap > .htnote-board').waitForDisplayed();    assert.equal(await $('.htnote-board-cell:nth-child(1)').getAttribute('data-htnote-cell'), '1 6 1');
    assert.equal(await $('.htnote-board-cell:nth-child(2)').getAttribute('data-htnote-cell'), '7 6 1');
    await (await visibleEditorContentControl('.tiptap > p:last-child')).click();
    await (await visibleEditorTool('[data-testid="insert-widget"]')).click(); await $('[data-testid="insert-checklist"]').click();
    await $('[data-testid="checklist-title"]').setValue("Moved checklist");
    await $('[data-testid="checklist-item"]').setValue("Saved item");
    const widgetGrip = await $('.tiptap .htnote-widget-handle');
    await browser.waitUntil(async () => browser.execute(() => {
      const editor = (document.querySelector('.tiptap') as HTMLElement & { editor: { getJSON: () => { content: { type: string; attrs?: { title?: string; items?: { text: string }[] } }[] } } }).editor;
      const widget = editor.getJSON().content.find((node) => node.type === 'checklist');
      return widget?.attrs?.title === 'Moved checklist' && widget.attrs.items?.[0]?.text === 'Saved item';
    }));
    await widgetGrip.scrollIntoView(); await waitForPointerStable(widgetGrip);
    const cellEnd = await browser.execute(() => { const rect = document.querySelector('.htnote-board-cell:first-child p')!.getBoundingClientRect(); return { x: Math.round(rect.left + rect.width / 2), y: Math.round(rect.bottom - 1) }; });
    await pointerDrag(widgetGrip, await $('.htnote-board-cell:first-child'), { toPoint: cellEnd, waypoints: [cellEnd], afterActivation: async () => { await $('.htnote-block-chip').waitForDisplayed(); } });
    await $('.htnote-board-cell:first-child .htnote-widget-handle').waitForDisplayed();
    const paragraph = await $('.htnote-board-cell:first-child > p'); await pointerMoveTo(paragraph); await handle.waitForDisplayed();
    const below = await browser.execute(() => { const rect = document.querySelector('.tiptap > p:last-child')!.getBoundingClientRect(); return { x: Math.round(rect.left + rect.width / 2), y: Math.round(rect.top + 1) }; });
    await pointerDrag(handle, await $('.tiptap > p:last-child'), { toPoint: below });
    await browser.waitUntil(async () => await $('.tiptap > p').getText() === "First block");
    const html = await saveAndView(note.id, (value) => value.includes("Saved item") && value.includes("First block"));
    assert.equal((html.match(/class="htnote-board-cell"/g) ?? []).length, 2);
    assert.match(html, /data-htnote-cell="1 6 1"[^>]*>\s*<div class="htnote-checklist"/);
    assert.match(html, /data-htnote-cell="7 6 1"[^>]*>\s*<p>Second block<\/p>/);
    assert.ok(html.indexOf("First block") > html.indexOf("Second block"));
    await editNote();
    assert.equal(await $('.tiptap > p').getText(), "First block");
    assert.equal(await $('.htnote-board-cell:first-child [data-testid="checklist-title"]').getValue(), "Moved checklist");
    await $('[data-testid="cancel-edit"]').click();
  });

  it("moves and resizes board cells with real pointer actions and saves their layouts", async () => {
    const note = await createNote("Board pointer round trip");
    await openNote(note.id); await editNote();
    await (await visibleEditorTool('[data-testid="insert-widget"]')).click();
    await $('[data-testid="insert-board"]').click();
    await (await visibleEditorContentControl('.htnote-board-cell:first-child p')).click(); await browser.keys("Pointer left");
    const right = await visibleEditorContentControl('.htnote-board-cell:nth-child(2) p');
    await right.click(); await browser.keys("Pointer right");
    await pointerMoveTo(right);
    const grip = await $('[data-testid="board-move"]'); await grip.waitForDisplayed();
    const destination = await browser.execute(() => {
      const board = document.querySelector('.tiptap .htnote-board')!.getBoundingClientRect();
      const step = (board.width + 16) / 12;
      return { x: Math.round(board.left + 7 * step + 4), y: Math.round(board.bottom + 24) };
    });
    await pointerDrag(grip, await $('.tiptap .htnote-board'), { toPoint: destination });
    await browser.waitUntil(async () => (await $('.tiptap .htnote-board-cell:nth-child(2)').getAttribute('data-htnote-cell')) === '8 5 2');
    const left = await visibleEditorContentControl('.htnote-board-cell:first-child p'); await left.click();
    const edgePoint = await browser.execute(() => { const cell = document.querySelector('.tiptap .htnote-board-cell')!.getBoundingClientRect(); return { x: Math.round(cell.right - 3), y: Math.round(cell.top + cell.height / 2) }; });
    await pointerMoveTo(left, edgePoint);
    const edge = await $('[data-testid="board-resize-right"]'); await edge.waitForDisplayed();
    const expanded = await browser.execute(() => {
      const board = document.querySelector('.tiptap .htnote-board')!.getBoundingClientRect();
      const cell = document.querySelector('.tiptap .htnote-board-cell')!.getBoundingClientRect();
      return { x: Math.round(board.left + 9 * (board.width + 16) / 12 - 16), y: Math.round(cell.top + cell.height / 2) };
    });
    await pointerDrag(edge, await $('.tiptap .htnote-board'), { toPoint: expanded });
    const html = await saveAndView(note.id, (value) => value.includes('data-htnote-cell="1 9 1"') && value.includes('data-htnote-cell="8 5 2"'));
    assert.ok(html.includes("Pointer left") && html.includes("Pointer right"));
    assert.equal((html.match(/class="htnote-board-cell"/g) ?? []).length, 2);
  });

  it("saves a board, changes its cell width and enhances the nested checklist", async () => {
    const note = await createNote("Board round trip");
    await openNote(note.id); await editNote();
    await (await visibleEditorTool('[data-testid="insert-widget"]')).click();
    await $('[data-testid="insert-board"]').click();
    await (await visibleEditorContentControl('.htnote-board-cell p')).click();
    await browser.keys("Left cell text");
    await (await visibleEditorContentControl('.htnote-board-cell:nth-child(2) p')).click();
    await (await visibleEditorTool('[data-testid="insert-widget"]')).click();
    assert.equal(await $('[data-testid="insert-board"]').getAttribute("aria-disabled"), "true");
    await $('[data-testid="insert-checklist"]').click();
    const title = await $('[data-testid="checklist-title"]'); await title.waitForDisplayed();
    await title.setValue("Board checklist"); await browser.keys("Enter");
    await $('[data-testid="checklist-item"]').setValue("Right cell item");
    // Widget girdisine odaklanınca, önceki metin hücresinin seçimi etkin kalmamalı.
    await (await visibleEditorContentControl('.htnote-board-cell:first-child p')).click();
    await (await visibleEditorContentControl('[data-testid="checklist-title"]')).click();
    await browser.keys(["Control", "Alt", "l"]);
    assert.equal(await $('[data-testid="board-layout"]').getAttribute("aria-pressed"), "true");
    await browser.keys("Escape");
    // Widget ile biten hücrede seçim tutamağı editör odağını hücrede tutar.
    await (await visibleEditorContentControl('.htnote-board-cell:nth-child(2) .htnote-widget-handle')).click();
    assert.equal(await $$('.htnote-board-cell:nth-child(2) > p').length, 0);
    await browser.keys("Enter");
    await browser.waitUntil(async () => await $$('.htnote-board-cell:nth-child(2) > p').length === 1);
    await browser.keys("Backspace");
    await browser.waitUntil(async () => await $$('.htnote-board-cell:nth-child(2) > p').length === 0);
    assert.equal(await $('.htnote-board-cell:nth-child(2) .ProseMirror-selectednode').isExisting(), true);
    await browser.keys(["Control", "z"]);
    await browser.waitUntil(async () => await $$('.htnote-board-cell:nth-child(2) > p').length === 1);
    await browser.keys("Backspace");
    await browser.keys("ArrowDown");
    assert.equal(await $('.htnote-board-cell:nth-child(2) .ProseMirror-gapcursor').isExisting(), true);
    await (await visibleEditorContentControl('.htnote-board-cell:first-child p')).click();
    const cell = await visibleEditorContentControl('.htnote-board-cell:nth-child(2)');
    const gapPoint = await browser.execute(() => {
      const bounds = document.querySelector('.tiptap .htnote-board-cell:nth-child(2)')!.getBoundingClientRect();
      return { x: Math.round(bounds.left + bounds.width / 2), y: Math.round(bounds.bottom - 4) };
    });
    await pointerClickAt(cell, gapPoint.x, gapPoint.y);
    assert.equal(await $('.htnote-board-cell:nth-child(2) .ProseMirror-gapcursor').isExisting(), true);
    await browser.keys("Cell note");
    assert.equal(await $('.htnote-board-cell:nth-child(2) > p').getText(), "Cell note");
    const layout = await $('[data-testid="board-layout"]'); await layout.waitForClickable(); await layout.click();
    // Shift+sol sağ kenarı bir birim daraltır; sağa genişletme ızgara sınırına tabidir.
    await browser.keys(["Shift", "ArrowLeft"]); await browser.keys("Escape");
    const html = await saveAndView(note.id, (value) => value.includes("Left cell text") && value.includes("Right cell item") && value.includes('data-htnote-cell="8 4 1"'));
    assert.equal((html.match(/class="htnote-board-cell"/g) ?? []).length, 2);
    assert.ok(html.includes('data-htnote-cell="1 7 1"'));
    assert.ok(html.includes('grid-column: 8 / span 4; grid-row: 1;'));
    await withNoteFrame(note.id, async () => {
      const checkbox = await $('.htnote-board-cell .htnote-checklist-items input'); await checkbox.waitForDisplayed();
      assert.equal(await checkbox.isSelected(), false); await checkbox.click(); assert.equal(await checkbox.isSelected(), true);
      await $('[data-testid="checklist-reset"]').click(); assert.equal(await checkbox.isSelected(), false);
      const copy = await $('[data-testid="checklist-copy"]'); await copy.click();
      await browser.waitUntil(async () => /Kopyalandı|Copied/.test(await copy.getText()));
      const positions = await browser.execute(() => Array.from(document.querySelectorAll('.htnote-board > .htnote-board-cell')).map((cell) => cell.getBoundingClientRect().x));
      assert.equal(positions.length, 2); assert.notEqual(positions[0], positions[1]);
    });
    assert.equal((await invoke<{ html: string }>("read_note", { id: note.id })).html, html);
    const exportedPath = join(root, "board-export.html");
    await invoke("export_single_html", { id: note.id, targetPath: exportedPath });
    const exported = (await waitForFile(exportedPath)).toString();
    assert.ok(exported.includes('data-htnote-cell="8 4 1"'));
    assert.ok(exported.includes('grid-template-columns: repeat(12, minmax(0, 1fr))'));
    assert.ok(!exported.includes("/__htnote/bridge.js"));
    await editNote(); assert.equal(await $('[data-testid="checklist-item"]').getValue(), "Right cell item");
    await $('[data-testid="cancel-edit"]').click();
  });

  it("saves a calculation, edits/copies/resets live values and keeps disk HTML unchanged", async () => {
    const note = await createNote("Calculation round trip");
    await openNote(note.id); await editNote();
    await (await visibleEditorTool('[data-testid="insert-widget"]')).click();
    await $('[data-testid="insert-calc"]').click();
    const title = await $('[data-testid="calc-title"]'); await title.waitForDisplayed();
    await title.setValue("Monthly budget"); await browser.keys("Enter");
    const source = "Kira = 18.500\nFatura = 2.340 + 870\nKDV = %20 * 4.000\n5/0\ntoplam";
    await $('[data-testid="calc-content"]').setValue(source);
    assert.equal(await $('[data-testid="calc-total"]').getText(), "22.510");
    const html = await saveAndView(note.id, (value) => value.includes("Monthly budget") && value.includes("KDV = %20"));
    assert.ok(html.includes('<textarea class="htnote-calc-input" spellcheck="false" rows="3">'));
    assert.ok(!html.includes("htnote-calc-node")); assert.ok(!html.includes("calc-results"));
    await withNoteFrame(note.id, async () => {
      const input = await $('.htnote-calc-input'); await input.waitForDisplayed();
      const copy = await $('[data-testid="calc-copy"]'), reset = await $('[data-testid="calc-reset"]');
      await browser.waitUntil(async () => (await copy.getText()).length > 0);
      assert.equal(await reset.isEnabled(), false);
      assert.equal(await $('[data-testid="calc-total"]').getText(), "22.510");
      assert.equal(await browser.execute(() => 'HTNOTE_CALC_ENGINE' in window || 'HTNOTE_TEMPLATE_ENGINE' in window), false);
      await input.setValue("0,1 + 0,2\n100 + %20");
      assert.equal(await $('[data-testid="calc-total"]').getText(), "120,3");
      await copy.click(); await browser.waitUntil(async () => /Kopyalandı|Copied/.test(await copy.getText()));
      await browser.execute(() => { const probe = document.createElement("textarea"); probe.id = "calc-probe"; document.body.append(probe); });
      const probe = await $('#calc-probe'); await probe.click(); await browser.keys(["Control", "v"]);
      await browser.waitUntil(async () => await probe.getValue() === "120,3");
      await browser.execute(() => document.getElementById("calc-probe")?.remove());
      await reset.click(); assert.equal(await input.getValue(), source);
      assert.equal(await $('[data-testid="calc-total"]').getText(), "22.510");
      assert.equal(await reset.isEnabled(), false);
      await input.setValue("999");
    });
    assert.equal((await invoke<{ html: string }>("read_note", { id: note.id })).html, html);
    assert.equal((await waitForFile(join(root, note.relPath, "index.html"))).toString(), html);
    await editNote(); assert.equal(await $('[data-testid="calc-content"]').getValue(), source);
    await $('[data-testid="cancel-edit"]').click();
  });

  it("saves a template, fills and copies repeated variables, resets and keeps disk HTML unchanged", async () => {
    const note = await createNote("Template round trip");
    await openNote(note.id); await editNote();
    await (await visibleEditorTool('[data-testid="insert-widget"]')).click();
    await $('[data-testid="insert-template"]').click();
    const title = await $('[data-testid="template-title"]'); await title.waitForDisplayed();
    await title.setValue("Customer response"); await browser.keys("Enter");
    const source = "Sayın {{Ad|Ahmet}}, {{AD}}\nNo: {{No}}\n<&>";
    await $('[data-testid="template-content"]').setValue(source);
    await (await visibleEditorContentControl('.htnote-widget-tools button')).click();
    await $('.htnote-color-popover button[aria-label="Nane"], .htnote-color-popover button[aria-label="Mint"]').click();
    const html = await saveAndView(note.id, (value) => value.includes("Customer response") && value.includes("{{Ad|Ahmet}}"));
    assert.ok(html.includes('<textarea class="htnote-template-source" spellcheck="false" rows="3">'));
    assert.ok(html.includes('data-htnote-bg="mint"'));
    assert.ok(!html.includes("htnote-template-node")); assert.ok(!html.includes("template-preview"));
    const exportedPath = join(root, "template-export.html");
    await invoke("export_single_html", { id: note.id, targetPath: exportedPath });
    const exported = (await waitForFile(exportedPath)).toString();
    assert.ok(exported.includes("{{Ad|Ahmet}}")); assert.ok(!exported.includes("/__htnote/bridge.js"));
    await withNoteFrame(note.id, async () => {
      const copy = await $('[data-testid="template-copy"]'); await copy.waitForExist();
      await browser.waitUntil(async () => (await copy.getText()).length > 0);
      const fields = await $$('[data-testid="template-variable"]');
      const reset = await $('[data-testid="template-reset"]');
      assert.equal(fields.length, 2); assert.equal(await fields[0].getValue(), "Ahmet");
      assert.equal(await reset.isEnabled(), false);
      assert.equal(await $('.htnote-template-source').isDisplayed(), false);
      await fields[0].setValue("Live <&>");
      const preview = await $('[data-testid="template-preview"]');
      assert.ok((await preview.getText()).includes("Sayın Live <&>, Live <&>"));
      await copy.click(); await browser.waitUntil(async () => /Kopyalandı|Copied/.test(await copy.getText()));
      await browser.execute(() => { const probe = document.createElement("textarea"); probe.id = "template-probe"; document.body.append(probe); });
      const probe = await $('#template-probe'); await probe.click(); await browser.keys(["Control", "v"]);
      await browser.waitUntil(async () => await probe.getValue() === "Sayın Live <&>, Live <&>\nNo: \n<&>");
      await browser.execute(() => document.getElementById("template-probe")?.remove());
      await fields[1].setValue("42");
      assert.ok((await preview.getText()).includes("No: 42"));
      await reset.click();
      assert.equal(await fields[0].getValue(), "Ahmet"); assert.equal(await fields[1].getValue(), "");
      assert.equal(await reset.isEnabled(), false);
      await fields[0].setValue("Unsaved viewer mutation");
    });
    assert.equal((await invoke<{ html: string }>("read_note", { id: note.id })).html, html);
    assert.equal((await waitForFile(join(root, note.relPath, "index.html"))).toString(), html);
    await browser.refresh(); await openNote(note.id);
    await withNoteFrame(note.id, async () => {
      const input = await $('[data-testid="template-variable"]'); await input.waitForExist();
      assert.equal(await input.getValue(), "Ahmet");
    });
    await editNote();
    assert.equal(await $('[data-testid="template-content"]').getValue(), source);
    await $('[data-testid="cancel-edit"]').click();
  });

  it("inserts and saves copy fields, copies rows/all and preserves the saved definition list", async () => {
    const note = await createNote("Copy fields round trip");
    await openNote(note.id); await editNote();
    await (await visibleEditorTool('[data-testid="insert-widget"]')).click();
    await $('[data-testid="insert-copyfields"]').click();
    const title = await $('[data-testid="copyfields-title"]'); await title.waitForDisplayed();
    await title.setValue("Server fields"); await browser.keys("Enter");
    await $('[data-testid="copyfields-label"]').setValue("Host");
    await browser.keys(["Shift", "Enter"]);
    assert.equal(await $('[data-testid="copyfields-label"]').getValue(), "Host");
    await browser.keys("Enter");
    assert.equal(await browser.execute(() => document.activeElement?.getAttribute("data-testid")), "copyfields-value");
    await $('[data-testid="copyfields-value"]').setValue("server <&> value");
    await browser.keys(["Shift", "Enter"]);
    assert.equal(await $('[data-testid="copyfields-value"]').getValue(), "server <&> value");
    assert.equal((await $$('[data-testid="copyfields-value"]')).length, 1);
    await browser.keys("Enter");
    await browser.waitUntil(async () => (await $$('[data-testid="copyfields-value"]')).length === 2);
    await (await $$('[data-testid="copyfields-value"]'))[1].setValue("unlabeled"); await browser.keys("Enter");
    await browser.waitUntil(async () => (await $$('[data-testid="copyfields-value"]')).length === 3);
    await (await $$('[data-testid="copyfields-label"]'))[2].setValue("Empty");
    await (await $$('[data-testid="copyfields-value"]'))[2].click(); await browser.keys("Enter");
    await browser.waitUntil(async () => (await $$('[data-testid="copyfields-value"]')).length === 4);
    await (await visibleEditorContentControl('.htnote-widget-tools button')).click();
    await $('.htnote-color-popover button[aria-label="Nane"], .htnote-color-popover button[aria-label="Mint"]').click();
    const html = await saveAndView(note.id, (value) => value.includes("Server fields") && value.includes("server &lt;&amp;&gt; value"));
    assert.match(html, /<dl class="htnote-copyfields-list"><div class="htnote-copyfields-row"><dt>Host<\/dt><dd>server &lt;&amp;&gt; value<\/dd>/);
    assert.ok(!html.includes("htnote-copyfields-node")); assert.ok(!html.includes("copyfields-copy-row"));
    assert.equal((html.match(/class="htnote-copyfields-row"/g) || []).length, 3);
    const exportedPath = join(root, "copyfields-export.html");
    await invoke("export_single_html", { id: note.id, targetPath: exportedPath });
    const exported = (await waitForFile(exportedPath)).toString();
    assert.ok(exported.includes('<dt>Host</dt><dd>server &lt;&amp;&gt; value</dd>'));
    assert.ok(!exported.includes("/__htnote/bridge.js"));
    await withNoteFrame(note.id, async () => {
      const copyAll = await $('[data-testid="copyfields-copy-all"]'); await copyAll.waitForExist();
      await browser.waitUntil(async () => (await copyAll.getText()).length > 0);
      await browser.execute(() => { const field = document.createElement("textarea"); field.id = "copyfields-probe"; document.body.append(field); });
      const probe = await $('#copyfields-probe');
      const verifyClipboard = async (expected: string) => {
        await probe.setValue(""); await probe.click(); await browser.keys(["Control", "v"]);
        await browser.waitUntil(async () => await probe.getValue() === expected);
      };
      const buttons = await $$('[data-testid="copyfields-copy-row"]');
      assert.equal(buttons.length, 2);
      await buttons[0].click();
      await browser.waitUntil(async () => /Kopyalandı|Copied/.test(await buttons[0].getText()));
      await verifyClipboard("server <&> value");
      await (await $$('.htnote-copyfields-row dd'))[1].doubleClick();
      await browser.waitUntil(async () => /Kopyalandı|Copied/.test(await buttons[1].getText()));
      await verifyClipboard("unlabeled");
      await copyAll.click(); await browser.waitUntil(async () => /Kopyalandı|Copied/.test(await copyAll.getText()));
      await verifyClipboard("Host: server <&> value\nunlabeled");
      await browser.waitUntil(async () => !/Kopyalandı|Copied/.test(await buttons[0].getText()));
      assert.equal(await (await $$('.htnote-copyfields-row dd'))[0].getText(), "server <&> value");
      await browser.execute(() => document.getElementById("copyfields-probe")?.remove());
    });
    assert.equal((await invoke<{ html: string }>("read_note", { id: note.id })).html, html);
    assert.equal((await waitForFile(join(root, note.relPath, "index.html"))).toString(), html);
    await editNote();
    assert.equal(await $('[data-testid="copyfields-title"]').getValue(), "Server fields");
    assert.equal((await $$('[data-testid="copyfields-value"]')).length, 3);
    assert.equal(await (await $$('[data-testid="copyfields-value"]'))[0].getValue(), "server <&> value");
    await $('[data-testid="cancel-edit"]').click();
  });

  it("saves checklist defaults, copies remaining items, resets and discards viewer checks on refresh", async () => {
    const note = await createNote("Checklist round trip");
    await openNote(note.id);
    await editNote();
    await (await visibleEditorTool('[data-testid="insert-widget"]')).click();
    await $('[data-testid="insert-checklist"]').click();
    const title = await $('[data-testid="checklist-title"]');
    await title.waitForDisplayed();
    await title.setValue("Release checklist");
    await browser.keys("Enter");
    assert.equal(await browser.execute(() => document.activeElement?.getAttribute("data-testid")), "checklist-item");
    await $('[data-testid="checklist-item"]').setValue("First <&> item");
    await browser.keys(["Shift", "Enter"]);
    assert.equal(await $('[data-testid="checklist-item"]').getValue(), "First <&> item");
    assert.equal((await $$('[data-testid="checklist-item"]')).length, 1);
    await $('.htnote-checklist-editor-row input[type="checkbox"]').click();
    await $('[data-testid="checklist-item"]').click();
    await browser.keys("End");
    await browser.keys("Enter");
    await browser.waitUntil(async () => (await $$('[data-testid="checklist-item"]')).length === 2);
    await (await $$('[data-testid="checklist-item"]'))[1].setValue("Second remaining");
    await browser.keys("Enter");
    await browser.waitUntil(async () => (await $$('[data-testid="checklist-item"]')).length === 3);
    await (await $$('[data-testid="checklist-item"]'))[2].setValue("Third remaining");
    await browser.keys("Enter");
    await browser.waitUntil(async () => (await $$('[data-testid="checklist-item"]')).length === 4);
    await (await visibleEditorContentControl('.htnote-widget-tools button')).click();
    await $('.htnote-color-popover button[aria-label="Nane"], .htnote-color-popover button[aria-label="Mint"]').click();
    const html = await saveAndView(note.id, (value) => value.includes("Release checklist") && value.includes("First &lt;&amp;&gt; item"));
    assert.match(html, /<div class="htnote-checklist" data-htnote-widget="checklist" data-htnote-bg="mint">/);
    assert.match(html, /<input type="checkbox" checked> First &lt;&amp;&gt; item/);
    assert.ok(!html.includes("htnote-checklist-node"));
    assert.ok(!html.includes("checklist-reset"));
    const exportedPath = join(root, "checklist-export.html");
    await invoke("export_single_html", { id: note.id, targetPath: exportedPath });
    const exported = (await waitForFile(exportedPath)).toString();
    assert.ok(exported.includes('<input type="checkbox" checked>'));
    assert.ok(exported.includes("Third remaining"));
    assert.ok(!exported.includes("/__htnote/bridge.js"));
    await withNoteFrame(note.id, async () => {
      const reset = await $('[data-testid="checklist-reset"]');
      await reset.waitForExist();
      const inputs = await $('.htnote-checklist-items').$$('input');
      assert.equal(await inputs[0].isSelected(), true);
      assert.equal(await reset.isEnabled(), false);
      assert.equal(await $('[data-testid="checklist-counter"]').getText(), "1 / 3");
      await inputs[1].click();
      assert.equal(await $('[role="progressbar"]').getAttribute("aria-valuenow"), "2");
      assert.equal(await reset.isEnabled(), true);
      const copy = await $('[data-testid="checklist-copy"]');
      await browser.waitUntil(async () => (await copy.getText()).length > 0);
      await copy.click();
      await browser.waitUntil(async () => /Kopyalandı|Copied/.test(await copy.getText()));
      // Gerçek sistem panosunu yerel bir alana yapıştırarak kalan metni doğrula.
      await browser.execute(() => {
        const field = document.createElement("textarea"); field.id = "checklist-clipboard-probe"; document.body.append(field);
      });
      const probe = await $('#checklist-clipboard-probe');
      await probe.click(); await browser.keys(["Control", "v"]);
      await browser.waitUntil(async () => await probe.getValue() === "Third remaining");
      await browser.execute(() => document.getElementById("checklist-clipboard-probe")?.remove());
      await reset.click();
      assert.equal(await inputs[0].isSelected(), true);
      assert.equal(await inputs[1].isSelected(), false);
      assert.equal(await reset.isEnabled(), false);
      await inputs[0].click();
      await inputs[2].click();
    });
    assert.equal((await invoke<{ html: string }>("read_note", { id: note.id })).html, html);
    assert.equal((await waitForFile(join(root, note.relPath, "index.html"))).toString(), html);
    await browser.refresh(); await openNote(note.id);
    await withNoteFrame(note.id, async () => {
      const inputs = await $('.htnote-checklist-items').$$('input');
      assert.equal(await inputs[0].isSelected(), true);
      assert.equal(await inputs[1].isSelected(), false);
      assert.equal(await inputs[2].isSelected(), false);
      assert.equal(await $('[data-testid="checklist-counter"]').getText(), "1 / 3");
    });
    await editNote();
    assert.equal(await $('[data-testid="checklist-title"]').getValue(), "Release checklist");
    const fields = await $$('[data-testid="checklist-item"]');
    assert.equal(fields.length, 3);
    assert.equal(await fields[0].getValue(), "First <&> item");
    assert.equal(await fields[2].getValue(), "Third remaining");
    await $('[data-testid="cancel-edit"]').click();
  });

  it("saves the editable atom, copies actual live text in WebView2, resets and discards viewer changes", async () => {
    const note = await createNote("Textbox round trip");
    await openNote(note.id);
    await editNote();
    await (await visibleEditorTool('[data-testid="insert-widget"]')).click();
    await $('[data-testid="insert-textbox"]').click();
    const title = await $('[data-testid="textbox-title"]');
    const content = await $('[data-testid="textbox-content"]');
    await title.waitForDisplayed();
    assert.equal(await title.getValue(), "");
    assert.equal(await content.getValue(), "");
    await title.setValue("Widget title");
    await browser.keys("Enter");
    assert.equal(await browser.execute(() => document.activeElement?.getAttribute("data-testid")), "textbox-content");
    const saved = "Saved first line\n<saved> & last line";
    await content.setValue(saved);
    await (await visibleEditorContentControl('.htnote-widget-tools button')).click();
    const mint = await $('.htnote-color-popover button[aria-label="Nane"], .htnote-color-popover button[aria-label="Mint"]');
    await mint.waitForDisplayed();
    await mint.click();
    const html = await saveAndView(note.id, (value) => value.includes("Widget title") && value.includes("&lt;saved&gt; &amp; last line"));
    assert.match(html, /<div class="htnote-textbox" data-htnote-widget="textbox" data-htnote-bg="mint">/);
    const savedDocument = await browser.execute((source) => {
      const doc = new DOMParser().parseFromString(source, "text/html");
      return { bodyBackground: doc.body.getAttribute("data-ht-bg"), appearance: doc.getElementById("htnote-appearance")?.textContent };
    }, html);
    assert.equal(savedDocument.bodyBackground, null);
    assert.ok(savedDocument.appearance?.includes("--ht-note-mint:"));
    const exportedPath = join(root, "widget-export.html");
    await invoke("export_single_html", { id: note.id, targetPath: exportedPath });
    const exported = (await waitForFile(exportedPath)).toString();
    assert.ok(exported.includes('data-htnote-bg="mint"'));
    assert.ok(exported.includes("--ht-note-mint:"));
    assert.ok(!exported.includes("/__htnote/bridge.js"));
    assert.match(html, /<textarea class="htnote-textbox-input" spellcheck="false" rows="3">Saved first line\n&lt;saved&gt; &amp; last line<\/textarea>/);
    assert.ok(!html.includes("htnote-textbox-actions"));
    assert.ok(!html.includes("htnote-textbox-node"));
    await waitForFile(join(root, note.relPath, "index.html"), (bytes) => bytes.toString().includes("Widget title"));
    const live = "Live clipboard text\n<temporary> & content";
    await withNoteFrame(note.id, async () => {
      const field = await $(".htnote-textbox-input");
      assert.equal(await field.getValue(), saved);
      assert.equal(await $(".htnote-textbox-title").getText(), "Widget title");
      const reset = await $('[data-testid="textbox-reset"]');
      await reset.waitForExist();
      assert.equal(await reset.isEnabled(), false);
      await field.setValue(live);
      assert.equal(await reset.isEnabled(), true);
      // Yalnız ölçüm: gerçek tarayıcı API'lerinin sonuçlarını kaydet, davranışı değiştirme.
      await browser.execute(() => {
        const audit: string[] = [];
        (window as unknown as { textboxCopyAudit: string[] }).textboxCopyAudit = audit;
        if (navigator.clipboard) {
          const write = navigator.clipboard.writeText.bind(navigator.clipboard);
          navigator.clipboard.writeText = async (value) => {
            try { await write(value); audit.push("clipboard.writeText:success"); }
            catch (error) { audit.push("clipboard.writeText:blocked"); throw error; }
          };
        }
        const exec = document.execCommand.bind(document);
        document.execCommand = (command, ...args) => {
          const result = exec(command, ...args);
          if (command === "copy") audit.push(`execCommand: ${result}`);
          return result;
        };
      });
      const copy = await $('[data-testid="textbox-copy"]');
      await browser.waitUntil(async () => (await copy.getText()).length > 0);
      await copy.click();
      await browser.waitUntil(async () => /Kopyalandı|Copied/.test(await copy.getText()));
      const audit = await browser.execute(() => (window as unknown as { textboxCopyAudit: string[] }).textboxCopyAudit);
      console.info("WebView2 textbox clipboard path:", audit.join(", "));
      assert.ok(audit.some((entry) => entry === "clipboard.writeText:success" || entry === "execCommand: true"));
      await reset.click();
      assert.equal(await field.getValue(), saved);
      assert.equal(await reset.isEnabled(), false);
      await field.setValue("");
      await field.click();
      await browser.keys(["Control", "v"]);
      await browser.waitUntil(async () => await field.getValue() === live, { timeoutMsg: "Actual clipboard paste did not match the live textarea content" });
      await reset.click();
      assert.equal(await field.getValue(), saved);
      await field.setValue("Unsaved viewer mutation");
    });
    assert.equal((await invoke<{ html: string }>("read_note", { id: note.id })).html, html);
    await browser.refresh();
    await openNote(note.id);
    await withNoteFrame(note.id, async () => {
      assert.equal(await $(".htnote-textbox-input").getValue(), saved);
    });
    await editNote();
    assert.equal(await $('[data-testid="textbox-title"]').getValue(), "Widget title");
    assert.equal(await $('[data-testid="textbox-content"]').getValue(), saved);
    await (await visibleEditorContentControl('.htnote-widget-tools button')).click();
    assert.equal(await $('.htnote-color-popover button[aria-label="Nane"], .htnote-color-popover button[aria-label="Mint"]').getAttribute("aria-pressed"), "true");
    await browser.keys("Escape");
    await $('[data-testid="cancel-edit"]').click();
  });
});
